# Generated by Django 6.0.3 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Explore Our Services', help_text='Text for the main action button', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Customized ICT solutions designed to scale with your business goals.', help_text='Sub-heading below the title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Empowering Your Digital Evolution', help_text='Main heading for the homepage', max_length=255),
        ),
    ]
