# Generated by Django 6.0.3 on 2026-03-26 00:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_cta_text_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'shield', 'cloud')"}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Agile Blue'), ('green', 'Agile Green'), ('slate', 'Agile Slate')]}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2), ('accent_color', 3)]], {})}),
        ),
    ]
