# Generated by Django 6.0.3 on 2026-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='expertise_label',
            field=models.CharField(default='Our Expertise', help_text='Small text above the main expertise heading', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_subtitle',
            field=models.TextField(default="Delivering excellence across PNG's digital landscape.", help_text='Description text next to the expertise heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_title',
            field=models.CharField(default='Integrated ICT Solutions', help_text='Large heading for the expertise section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vendor_label',
            field=models.CharField(default='Strategic Partners & Vendors', help_text='Small text above the moving vendor logos', max_length=255),
        ),
    ]
