# Generated by Django 6.0.3 on 2026-03-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_expertise_label_homepage_expertise_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='expertise_label',
        ),
    ]
