# Generated by Django 6.0.3 on 2026-03-27 00:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_expertise_label'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text="Main heading for the services page (e.g., 'Our Services')", max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Sub-heading below the title')),
                ('services', wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'shield', 'cloud')"}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Agile Blue'), ('green', 'Agile Green'), ('slate', 'Agile Slate')]}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2), ('accent_color', 3)]], {})})),
                ('cta_title', models.CharField(blank=True, help_text="Call to action title at the bottom (e.g., 'Ready to transform your IT?')", max_length=255)),
                ('cta_button_text', models.CharField(blank=True, help_text='Text for the contact button', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
