# Generated by Django 6.0.3 on 2026-03-27 03:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='expertise_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='expertise_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='vendor_label',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_button_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_subtitle',
            field=models.TextField(blank=True, default='Connect with our engineers to discuss your next project.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_title',
            field=models.CharField(default='Ready to modernize your infrastructure?', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_cta_text',
            field=models.CharField(default='View All News', help_text='Text for the link to the insights page', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_title',
            field=models.CharField(default='Latest Insights', help_text='Title for the news/insights section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_pillars',
            field=wagtail.fields.StreamField([('pillar', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'shield', 'zap', 'server')"}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle explaining your core differentiator'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_title',
            field=models.CharField(default='The Agile Advantage', help_text='Title for the value proposition section', max_length=255),
        ),
    ]
