# Generated by Django 6.0.3 on 2026-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_expertise_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='expertise_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Discover Our Services', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vendor_label',
            field=models.CharField(blank=True, default='Our Strategic Partners', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_title',
            field=models.CharField(help_text="Main heading (e.g., 'Our Services')", max_length=255),
        ),
    ]
