# Generated by Django 6.0.3 on 2026-03-27 05:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_expertise_subtitle_homepage_expertise_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Short label for the bottom tab (e.g., 'Cloud Computing')", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this slide', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Sub-heading description', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Explore More', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('tab_label', 0), ('title', 1), ('subtitle', 2), ('cta_text', 3)]], {})}, help_text='Add up to 4 slides for the hero slider'),
        ),
    ]
