# Generated by Django 6.0.3 on 2026-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bottom_cta_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bottom_cta_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bottom_cta_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_slides',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='insights_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='insights_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='value_pillars',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='value_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='value_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Explore Our Services', help_text='Text for the main action button', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Customized ICT solutions designed to scale with your business goals.', help_text='Sub-heading below the title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Empowering Your Digital Evolution', help_text='Main heading for the homepage', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_subtitle',
            field=models.TextField(default="Delivering excellence across PNG's digital landscape.", help_text='Description text next to the expertise heading'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_title',
            field=models.CharField(default='Integrated ICT Solutions', help_text='Large heading for the expertise section', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vendor_label',
            field=models.CharField(default='Strategic Partners & Vendors', help_text='Small text above the moving vendor logos', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_button_text',
            field=models.CharField(blank=True, help_text='Text for the contact button', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_title',
            field=models.CharField(blank=True, help_text="Call to action title at the bottom (e.g., 'Ready to transform your IT?')", max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_title',
            field=models.CharField(help_text="Main heading for the services page (e.g., 'Our Services')", max_length=255),
        ),
    ]
