# Generated by Django 6.0.3 on 2026-03-28 01:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_bottom_cta_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Text for the bottom tab (e.g., 'Enterprise Compute')", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Get a Quote'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('tab_name', 0), ('title', 1), ('subtitle', 2), ('cta_text', 3), ('image', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_subtitle',
            field=models.TextField(default='Delivering excellence across your digital landscape.', help_text='Description text next to the expertise heading'),
        ),
    ]
