# Generated by Django 6.0.3 on 2026-03-28 05:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Short sub-benefit description (e.g., 'Craft a cloud strategy that delivers value.')", 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'shield', 'cloud')", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 1), ('description', 2), ('icon', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services',
            field=wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Short sub-benefit description (e.g., 'Craft a cloud strategy that delivers value.')", 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'shield', 'cloud')", 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 1), ('description', 2), ('icon', 3)]], {})}),
        ),
    ]
