# Generated by Django 6.0.3 on 2026-03-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_services_alter_servicespage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='animated_conjunction',
            field=models.CharField(default='and', help_text='Connecting word before the last phrase', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_headline_intro',
            field=models.CharField(default='Agile ICT Solutions helps enterprises', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_headline_outro',
            field=models.CharField(default='so they stay ahead in a fast-changing world.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_subword_1',
            field=models.CharField(default='infrastructure', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_subword_2',
            field=models.CharField(default='operations', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_subword_3',
            field=models.CharField(default='networks', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_word_1',
            field=models.CharField(default='modernize', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_word_2',
            field=models.CharField(default='optimize', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='animated_word_3',
            field=models.CharField(default='secure', max_length=50),
        ),
    ]
