# Generated by Django 6.0.3 on 2026-03-31 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_animated_conjunction_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose the page to link to (e.g., the About page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_text',
            field=models.CharField(default='Who We Are', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_description',
            field=models.TextField(default='We bridge the gap between complex global technologies and local enterprise needs. By designing resilient infrastructure, we empower organizations to operate with absolute confidence.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Background image for the fixed banner section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default="Architecting PNG's Digital Future", max_length=255),
        ),
    ]
