# Generated by Django 6.0.3 on 2026-03-31 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_banner_cta_link_homepage_banner_cta_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='promo_card_link',
            field=models.ForeignKey(blank=True, help_text='Where should the promo image cards link to? (e.g., Services Page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_card_text',
            field=models.CharField(default='Explore Solutions', help_text='Text for the large image promo cards', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_card_cta',
            field=models.CharField(default='Learn More', help_text='Text for the button inside each service card', max_length=50),
        ),
    ]
