# Generated by Django 6.0.3 on 2026-03-31 01:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_promo_card_link_homepage_promo_card_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_button_text',
            field=models.CharField(default='Get a free quote', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_description',
            field=models.TextField(default='Partner with our engineering team to modernize your infrastructure. We provide precise technical scoping and local expertise to ensure your next project is built for scale and resilience.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose the page to link to (e.g., the Contact page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_title',
            field=models.CharField(default='Tailored Solutions for Your Enterprise', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_cta_link',
            field=models.ForeignKey(blank=True, help_text='Where should the FAQ CTA link to?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_cta_text',
            field=models.CharField(default="Explore All FAQ's", help_text='Text for the link at the bottom of the FAQs', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_section_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The FAQ question', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'The answer to the FAQ', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
    ]
