# Generated by Django 6.0.3 on 2026-03-31 01:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_bottom_cta_button_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='careers_cta_link',
            field=models.ForeignKey(blank=True, help_text='Where should the careers button link to? (e.g., Careers/Jobs page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='careers_cta_text',
            field=models.CharField(default='Browse job listings', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='careers_heading',
            field=models.CharField(default='Drive your career forward. Fast.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='careers_image',
            field=models.ForeignKey(blank=True, help_text='Optional: Upload a photo here to override the default graphic. Leave blank to use the default racer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_box_heading',
            field=models.CharField(default="Let's build it.", max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_box_hover_text',
            field=models.CharField(default='Engage our team', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_heading',
            field=models.CharField(default='Architecting the future.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_link',
            field=models.ForeignKey(blank=True, help_text='Where should this CTA block link to? (e.g., Contact Page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_cta_subheading',
            field=models.CharField(default='Infrastructure Deployment', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights',
            field=wagtail.fields.StreamField([('insight', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the insight', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short summary of the insight', 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional: Select the full blog/insight page to link to', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_cta_link',
            field=models.ForeignKey(blank=True, help_text="Where should 'View All Insights' link to? (e.g., Blog Index Page)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_cta_text',
            field=models.CharField(default='View All Insights', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_heading',
            field=models.CharField(default='Industry Insights', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='insights_subheading',
            field=models.CharField(default='2026 Horizon', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_heading_line_1',
            field=models.CharField(default='Success', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_heading_line_2',
            field=models.CharField(default='Stories', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_subheading',
            field=models.CharField(default='Enterprise', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'The testimonial text', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., James Morebi', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., PNG National Finance', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the left side of the slider', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author_name', 1), ('author_company', 2), ('image', 3)]], {})}),
        ),
    ]
