# Generated by Django 6.0.3 on 2026-04-01 05:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homepage_careers_cta_link_homepage_careers_cta_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_line_1',
            field=models.CharField(default='Digital', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_line_2_outline',
            field=models.CharField(default='Infrastructure', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='hero_line_3',
            field=models.CharField(default='Evolution', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='animated_conjunction',
            field=models.CharField(default='and', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_description',
            field=models.TextField(default='We bridge the gap between global technologies and local needs.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bottom_cta_description',
            field=models.TextField(default='Partner with our engineering team.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bottom_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bottom_cta_title',
            field=models.CharField(default='Tailored Solutions', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='careers_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='careers_heading',
            field=models.CharField(default='Drive your career forward.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='careers_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_subtitle',
            field=models.TextField(default='Delivering excellence across your digital landscape.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='expertise_title',
            field=models.CharField(default='Integrated ICT Solutions', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faq_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faq_cta_text',
            field=models.CharField(default="Explore All FAQ's", max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='insights',
            field=wagtail.fields.StreamField([('insight', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='insights_cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_card_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_card_text',
            field=models.CharField(default='Explore Solutions', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_card_cta',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short sub-benefit description for the grid card.', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'server')", 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the detail view hero (e.g., the high-tech abstract image).', 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'The square image shown in the detail view sidebar (e.g., the actual hardware/service photo).', 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'First paragraph of the technical scope.', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Second paragraph of the technical scope.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': "Technical tags (e.g., 'Infrastructure', 'Scaling', 'Optimization')"}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 1), ('description', 2), ('icon', 3), ('detail_image', 4), ('secondary_image', 5), ('process_1', 6), ('process_2', 7), ('tags', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author_name', 1), ('author_company', 2), ('image', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='vendor_label',
            field=models.CharField(default='Strategic Partners & Vendors', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='cta_title',
            field=models.CharField(blank=True, help_text="e.g., 'Ready to Initiate?'", max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services',
            field=wagtail.fields.StreamField([('service', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short sub-benefit description for the grid card.', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide icon name (e.g., 'cpu', 'server')", 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the detail view hero (e.g., the high-tech abstract image).', 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'The square image shown in the detail view sidebar (e.g., the actual hardware/service photo).', 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'First paragraph of the technical scope.', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Second paragraph of the technical scope.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': "Technical tags (e.g., 'Infrastructure', 'Scaling', 'Optimization')"}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 1), ('description', 2), ('icon', 3), ('detail_image', 4), ('secondary_image', 5), ('process_1', 6), ('process_2', 7), ('tags', 9)]], {})}),
        ),
    ]
