# Generated by Django 6.0.3 on 2026-04-01 06:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_servicespage_hero_subtitle_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_cta_link',
            field=models.ForeignKey(blank=True, help_text='About page link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='bottom_cta_title',
            field=models.CharField(default='Tailored Solutions for Your Enterprise', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='careers_heading',
            field=models.CharField(default='Drive your career forward. Fast.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faqs',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the bottom tab', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Get a Quote'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('tab_name', 0), ('title', 1), ('subtitle', 2), ('cta_text', 3), ('image', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_card_link',
            field=models.ForeignKey(blank=True, help_text='Services page link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short sub-benefit description', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide icon name', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 1), ('description', 2), ('icon', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background for the detail hero', 'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Sidebar square image', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Technical tags'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('short_benefit', 0), ('description', 1), ('icon', 2), ('detail_image', 3), ('secondary_image', 4), ('process_1', 1), ('process_2', 1), ('tags', 6)]], {})}),
        ),
    ]
